#!/usr/bin/env python3
"""Generate src/atlas.md from data/atlas.toml and templates/atlas.md.in.

    python3 tools/gen_atlas.py            write src/atlas.md
    python3 tools/gen_atlas.py --check    fail if src/atlas.md differs from what the data gives

The data file is the only place an atlas fact is written. Every table on the page
is rendered from it, so a fact changes in one place and the page follows.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "atlas.toml"
TEMPLATE = ROOT / "templates" / "atlas.md.in"
OUT = ROOT / "src" / "atlas.md"
HEADER = "<!-- GENERATED by tools/gen_atlas.py from data/atlas.toml; edit the data, not this file. -->\n"

LABEL_CLASS = {"published": "published", "open": "open", "proposed": "proposed",
               "draft": "draft", "individual draft": "draft"}


def cell(text: str) -> str:
    return text.replace("|", "\\|")


def table(header: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(cell(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def label(text: str) -> str:
    return f"[{text}]{{.label .{LABEL_CLASS[text]}}}"


def entry_status(e: dict) -> str:
    parts = [e["status"]] if e.get("status") else []
    if "stars" in e:
        parts.append(f"{e['stars']:,} stars")
    return "; ".join(parts)


def render(d: dict) -> str:
    layers, entries, mechs = d["layer"], d["entry"], d["mechanism"]
    names = {l["id"]: f"{i}. {l['name']}" for i, l in enumerate(layers, 1)}

    layer_table = table(
        ["layer", "the question it answers", "a working instance establishes", "it cannot establish on its own"],
        [[names[l["id"]], l["short_question"], l["short_establishes"], l["short_cannot"]] for l in layers])

    mech_rows = []
    for m in mechs:
        where = names.get(m["layer"], "the open cell")
        mech_rows.append([m["name"], where, m["writer"], m["establishes"], m["cannot"]])
    mechanism_table = table(["mechanism", "layer", "writer", "establishes", "cannot establish"], mech_rows)

    sections = []
    for i, l in enumerate(layers, 1):
        rows = [[f"[{e['name']}]({e['url']})", entry_status(e)] for e in entries if e["layer"] == l["id"]]
        nxt = layers[i]["name"] if i < len(layers) else layers[0]["name"]
        seam_title = f"Seam to layer {i + 1}" if i < len(layers) else "Seam back to layer 1"
        sections.append("\n\n".join([
            f"## {i}. {l['name']}",
            f"**Question.** {l['question']}",
            f"**Establishes.** {l['establishes']}",
            f"**Cannot establish.** {l['cannot']}",
            table(["project or standard", "status or size, read 2026-09-27"], rows),
            f"**{seam_title} ({nxt.lower()}).** {l['seam']}",
        ]))

    artifact_table = table(
        ["artifact", "layer", "release, read 2026-09-27", "what it does", "what it does not do"],
        [[f"[{a['name']}]({a['url']})", a["layers"], f"{a['release']} {label(a['label'])}", a["does"], a["does_not"]]
         for a in d["artifact"]])

    corpora = d["corpus"]
    corpus_table = table(
        ["corpus", "members", "split", "what it tests"],
        [[f"`{c['dir']}`", str(c["members"]), c["split"], c["tests"]] for c in corpora])

    contribution_table = table(
        ["where", "what", "state, read 2026-09-27"],
        [[f"[{c['where']}]({c['url']})", c["what"], f"{label(c['label'])} {c['state']}"] for c in d["contribution"]])

    listing_table = table(
        ["listing", "what", "state"],
        [[f"[{x['where']}]({x['url']})", x["what"], label(x["label"])] for x in d["listing"]])

    values = {
        "version": d["meta"]["version"],
        "read_window": d["meta"]["read_window"],
        "n_layers": str(len(layers)),
        "n_entries": str(len(entries)),
        "n_mechanisms": str(len(mechs)),
        "n_vectors": f"{sum(c['members'] for c in corpora):,}",
        "n_corpora": str(len(corpora)),
        "layer_table": layer_table,
        "mechanism_table": mechanism_table,
        "layer_sections": "\n\n".join(sections),
        "artifact_table": artifact_table,
        "corpus_table": corpus_table,
        "contribution_table": contribution_table,
        "listing_table": listing_table,
    }
    text = TEMPLATE.read_text(encoding="utf-8")
    for key, value in values.items():
        text = text.replace("{{" + key + "}}", value)
    if "{{" in text:
        raise SystemExit("unfilled placeholder in the atlas template")
    # Keep the YAML front matter first, as pandoc requires; the header follows it.
    front, sep, body = text.partition("\n---\n")
    return front + sep + HEADER + body


def main() -> int:
    d = tomllib.loads(DATA.read_text(encoding="utf-8"))
    text = render(d)
    if "--check" in sys.argv[1:]:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("src/atlas.md is out of date with data/atlas.toml: run python3 tools/gen_atlas.py")
            return 1
        print("src/atlas.md matches data/atlas.toml")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote src/atlas.md: {len(d['layer'])} layers, {len(d['entry'])} entries, "
          f"{len(d['mechanism'])} mechanisms, {len(d['corpus'])} corpora")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
